server:
  port: ${SERVER_PORT:8008}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/s4a}

spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:s4a_dev
    username: sa
    password:
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev

---
spring:
  datasource:
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_NAME:s4a}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: test

